#!/bin/sh
# File generated by ocamlbuild

cd /home/arthur/Desktop/ocaml_test/freq/_build

rm -f counter.cmi
rm -f counter.cmo
rm -f counter.ml.depends
rm -f counter.mli.depends
rm -f freq.cmi
rm -f freq.cmo
rm -f freq.ml.depends
rm -f freq.mli.depends
# Also clean the script itself
rm -f /home/arthur/Desktop/ocaml_test/freq/_build/_build/sanitize.sh
