#!/bin/sh
# File generated by ocamlbuild

cd /home/arthur/Desktop/ocaml_test

rm -f counter.cmi
rm -f counter.cmo
rm -f test.cmi
rm -f test.cmx
rm -f test.o
# Also clean the script itself
rm -f /home/arthur/Desktop/ocaml_test/_build/sanitize.sh
